# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #808080;")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 701, 121))
        self.frame.setStyleSheet("background-color: #f66867")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 30, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #fff;")
        self.label.setObjectName("label")
        self.input_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.input_amount.setGeometry(QtCore.QRect(150, 240, 380, 60))
        self.input_amount.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: #fff;")
        self.input_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.input_amount.setObjectName("input_amount")
        self.output_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.output_amount.setGeometry(QtCore.QRect(150, 400, 380, 60))
        self.output_amount.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30;\n"
"color: #fff;\n"
"")
        self.output_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.output_amount.setObjectName("output_amount")
        self.input_currency = QtWidgets.QComboBox(self.centralwidget)
        self.input_currency.setGeometry(QtCore.QRect(150, 160, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Felix Titling")
        font.setPointSize(10)
        self.input_currency.setFont(font)
        self.input_currency.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"color: #fff;")
        self.input_currency.setObjectName("input_currency")
        self.input_currency.addItem("")
        self.input_currency.addItem("")
        self.input_currency.addItem("")
        self.output_currency = QtWidgets.QComboBox(self.centralwidget)
        self.output_currency.setGeometry(QtCore.QRect(150, 320, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Felix Titling")
        font.setPointSize(10)
        self.output_currency.setFont(font)
        self.output_currency.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"color: #fff;")
        self.output_currency.setObjectName("output_currency")
        self.output_currency.addItem("")
        self.output_currency.addItem("")
        self.output_currency.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 480, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Felix Titling")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"color: #fff;")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Конвертер валют"))
        self.label.setText(_translate("MainWindow", "Конвертер валют"))
        self.input_currency.setItemText(0, _translate("MainWindow", "RUB"))
        self.input_currency.setItemText(1, _translate("MainWindow", "USD"))
        self.input_currency.setItemText(2, _translate("MainWindow", "EUR"))
        self.output_currency.setItemText(0, _translate("MainWindow", "RUB"))
        self.output_currency.setItemText(1, _translate("MainWindow", "USD"))
        self.output_currency.setItemText(2, _translate("MainWindow", "EUR"))
        self.pushButton.setText(_translate("MainWindow", "КОНВЕРТИРОВАТЬ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
